### PR TITLE
Footer Fixed and enhanced

### LINKED ISSUE #96: Footer Improvement
Currently the footer is not having the optimal Text size and font size , also the logos are too big and the Twitter logo is old and the line 'LinkedIn content patient Made Easy' should not be in centre so basically it can be made better with some modifications. 
I would like to work on this issue. 
Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.
Screenshot 2024-10-15 095107

### PR DESCRIPTION
**Pull request by Bhum-ika**
Fixed #96 

Following modifications made:
1. Website Logo changed
2. Twitter Logo changed to X
3. Added hover effects
4. Added Insta and Facebook logo
5. Made sure it Is responsive

image
Screenshot 2024-10-19 161925

Kindly add the tags while merging too.

**If you like the changes I have made, kindly upgrade my level. I would really appreciate**
If you have further queries in this issue, I am ready to help

### CODE REVIEW

File: components/landing-page/Footer.tsx [hunk 1]
```diff
@@ -10,92 +13,74 @@ const Footer = () => {
...
-          <div className="flex flex-col gap-4 justify-center items-center">
-            <h2 className="text-3xl font-semibold">Quick Links</h2>
-            <ul className="md:space-y-2 text-xl max-md:flex justify-center items-center space-x-4">
+          <div className="flex flex-col gap-4 justify-center md:items-center mt-5 md:mt-0">
+           <div className="space-y-2">
+           <h2 className="text-3xl font-semibold ">Quick Links</h2>
+            <ul className="md:space-y-2 text-xl max-md:flex  space-x-4 md:space-x-0  md:px-2 text-[#E5D9F2]">
               <li>
-                <a href="#" className="hover:underline">
+                <a href="#" className="hover:underline hover:text-[#fff]">
```
Comment (sudhanshutech) [inline components/landing-page/Footer.tsx:59]: how does this hover looks @Bhum-ika , can you provide a recording ?

Comment (Bhum-ika) [reply components/landing-page/Footer.tsx:59]: The links under 'quick links' are of light violet color and when u hover on them, their color will change to white

**Comment by himeshparashar** [comment]
@sudhanshutech once reviewed give a green signal

**Comment by Bhum-ika** [comment]
Hi @himeshparashar 
If you get a green signal, please upgrade it to level 2
I really put in good efforts here.

File: components/landing-page/Footer.tsx (hunk 1 above)
Comment (sudhanshutech) [reply components/landing-page/Footer.tsx:59]: ok make sense will you also provide a quick recording so we can have a look on the changes?

Comment (Bhum-ika) [reply components/landing-page/Footer.tsx:59]: Okay

Comment (Bhum-ika) [reply components/landing-page/Footer.tsx:59]: Uploading Social Morph - Google Chrome 2024-10-20 20-55-34.mp4…

File: components/landing-page/Footer.tsx [hunk 2]
```diff
@@ -10,92 +13,74 @@ const Footer = () => {
...
                 aria-label="LinkedIn"
               >
                 <FaLinkedin />
               </a>
-              <a  className = "hover:text-blue-400" href="https://x.com/himesh_dev" aria-label="Twitter">
-                <FaTwitter />
+              <a  className = "hover:text-white text-[#E5D9F2] border-2 border-[#E5D9F2] rounded-full p-2 hover:border-[#fff]" href="https://x.com/himesh_dev" aria-label="Twitter">
+                <FaXTwitter />
+              </a>
+              <a  className = "hover:text-white text-[#E5D9F2] border-2 border-[#E5D9F2] rounded-full p-2 hover:border-[#fff]" href="https://x.com/himesh_dev" aria-label="Twitter">
```
Comment (sudhanshutech) [inline components/landing-page/Footer.tsx:37]: @himeshparashar do we need to add these two additional platforms instagram and facebook because it doen't make sense to add same link for twitter to these platforms. So for now we can comment them until we ready to show those. Make sense @himeshparashar @Bhum-ika ? Otherwise the pr looks good to me.

File: components/landing-page/Footer.tsx (hunk 1 above)
Comment (sudhanshutech) [reply components/landing-page/Footer.tsx:59]: thanks

File: components/landing-page/Footer.tsx (hunk 2 above)
Comment (himeshparashar) [reply components/landing-page/Footer.tsx:37]: np @sudhanshutech i will add the links to this

**Comment by Bhum-ika** [comment]
Thank you
